# use python:3.6 as image



# add a "author" label



# install the following packages with pip3: flask, redis, requests, uwsgi



# copy the startscript (cmd.sh) in the image



# copy the app folder (./app) in the image



# Expose the ports 9090 9091



# Start the application script
