# Multistaging

# Stage 0:
#   - inherit from "openjdk:11-jdk"
#   - burn "Countdown.java" to "/docker_workshop"
#   - compile it

# Stage 1:
#   - inherit from "openjdk:11-jre"
#   - take over compiled app from stage 0 to enable the following CMD command

CMD ["java", "docker_workshop.Countdown"]
