# Multistaging

# Step 1: create image that generate the compiled java App (image = openjdk:11-jdk)



# Step 2: create new image. Copy compiled app from other image inside this one and run it.  (image = openjdk:11-jre)







# Run the app
CMD ["java", "workshop.Countdown"]

# Hint:
# The compiled app needs to be located in ./workshop/Countdown.class