# Multistaging

# Step 1: create image. copy the Countdown.java inside. Compile it. (image = openjdk:11-jdk)






# Step 2: create new image. Copy compiled app from other image inside this one and run it.  (image = openjdk:11-jre)










# Run the app
CMD ["java", "workshop.Countdown"]

# Hint:
# The compiled app needs to be located in ./workshop/Countdown.class