# Specify base image "xcellenthub/whalesay:latest" (FROM)

# Install apt package "fortunes" (RUN)

# Specify start command "/usr/games/fortune | cowsay" (CMD, use shell form since we use the pipe operator)
