
  elasticsearch:
    image: elasticsearch:7.0.0
    container_name: elasticsearch
    environment:
      - node.name=localhost
      - discovery.seed_hosts=localhost
      - cluster.initial_master_nodes=localhost
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - LOGSPOUT=ignore
    ports:
      - "9200:9200"
