---
version: "3.5"

services:
  logspout:
    image: amouat/logspout-logstash
    container_name: logspout
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      ROUTE_URIS: logstash+tcp://logstash:5000
    ports:
      - "8000:80"
